// Checks that what the hand-written docs cite still exists in the code base:
//   - `npm run <script>` / `npm start` / `npm test`: the script is in package.json;
//   - file paths in backticks (`src/…`, `docs/…`, `forge.config.ts`, `cbz-archive.test.ts`…): the
//     file or directory exists (bare file names and partial paths match any tracked file ending so);
//   - `vitest run -t "<name>"`: a test with that name exists;
//   - relative Markdown links and CLAUDE.md `@imports` in files outside docs/ (VitePress already
//     fails the build on dead links inside docs/).
// Exits with code 1 and lists every problem otherwise.
import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const rel = (file) => path.relative(root, file).replaceAll(path.sep, '/');

// Tracked files plus new, not-ignored ones (so a check run before `git add` sees them too).
const knownFiles = execFileSync('git', ['ls-files', '--cached', '--others', '--exclude-standard'], {
  cwd: root,
  encoding: 'utf-8',
})
  .split('\n')
  .filter(Boolean)
  .filter((file) => existsSync(path.join(root, file)));
const knownDirs = new Set(knownFiles.flatMap((file) => file.split('/').slice(0, -1).map((_, i, parts) => parts.slice(0, i + 1).join('/'))));

function docFiles() {
  const files = ['README.md', 'CLAUDE.md', 'CONTRIBUTING.md'].map((file) => path.join(root, file));
  const walk = (dir, skip) => {
    if (!existsSync(dir)) return;
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (!skip.includes(rel(full))) walk(full, skip);
      } else if (entry.name.endsWith('.md')) {
        files.push(full);
      }
    }
  };
  walk(path.join(root, 'docs'), ['docs/reference', 'docs/.vitepress']);
  walk(path.join(root, '.claude', 'commands'), []);
  return files.filter((file) => existsSync(file));
}

const scripts = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf-8')).scripts ?? {};

// Files that only exist at runtime or in a build, cited on purpose in the docs.
const RUNTIME_PATHS = [
  /^docs\/reference(\/|$)/, // generated by `npm run docs:gen` / `docs:api`
  /^docs\/\.vitepress\/(dist|cache)(\/|$)/,
  /^\.vite\//,
  /^out\//,
  /^node_modules\//,
];
const FILE_LIKE = /^[\w.@-]+(\/[\w.@[\]-]+)*\/?$/;
const CHECKED_EXTENSIONS = /\.(ts|tsx|mts|mjs|md|yml|yaml|css|html)$/;
const TOP_LEVEL = /^(src|docs|scripts|\.github|\.claude)\//;

function pathExists(candidate) {
  const clean = candidate.replace(/\/$/, '');
  if (existsSync(path.join(root, clean))) return true;
  // Partial paths ("main/ipc/comic.ts", "routes/settings/", "database.ts"): any known file or
  // directory ending with it.
  return knownFiles.some((file) => file === clean || file.endsWith(`/${clean}`)) ||
    [...knownDirs].some((dir) => dir === clean || dir.endsWith(`/${clean}`));
}

let testSources;
function testNameExists(name) {
  testSources ??= knownFiles.filter((file) => file.endsWith('.test.ts')).map((file) => readFileSync(path.join(root, file), 'utf-8'));
  // `vitest -t` matches test names by pattern, so a substring of a test name is enough.
  return testSources.some((source) =>
    [...source.matchAll(/\b(?:it|test|describe)\(\s*(['"`])(.*?)\1/g)].some((match) => match[2].includes(name)),
  );
}

const problems = [];
for (const file of docFiles()) {
  const text = readFileSync(file, 'utf-8');
  const report = (index, message) => {
    const line = text.slice(0, index).split('\n').length;
    problems.push(`${rel(file)}:${line}: ${message}`);
  };

  // npm scripts, anywhere (prose, inline code, code blocks).
  for (const match of text.matchAll(/\bnpm (?:run ([\w:-]+)|(start|test)\b)/g)) {
    const name = match[1] ?? match[2];
    if (!(name in scripts)) report(match.index, `npm script "${name}" doesn't exist in package.json`);
  }

  // Test names given to `vitest -t`.
  for (const match of text.matchAll(/vitest run -t "([^"]+)"/g)) {
    if (!testNameExists(match[1])) report(match.index, `no test named "${match[1]}"`);
  }

  // Paths in inline code spans and in code blocks.
  const spans = [
    ...[...text.matchAll(/`([^`\n]+)`/g)].map((m) => ({ value: m[1], index: m.index })),
    ...[...text.matchAll(/```[\w-]*\n([\s\S]*?)```/g)].flatMap((block) =>
      [...block[1].matchAll(/(?:^|\s)((?:src|docs|scripts)\/[\w./@-]+)/g)].map((m) => ({ value: m[1], index: block.index })),
    ),
  ];
  for (const { value, index } of spans) {
    const candidate = value.trim();
    if (!FILE_LIKE.test(candidate) || candidate.includes('..') || candidate.includes('NNNN')) continue;
    // Outside the top-level source directories, only source-like extensions are checked: other
    // names (main.js, db-location.json, tankobon.db…) are runtime files cited on purpose.
    if (!TOP_LEVEL.test(candidate) && !CHECKED_EXTENSIONS.test(candidate)) continue;
    if (RUNTIME_PATHS.some((pattern) => pattern.test(candidate))) continue;
    if (candidate.startsWith('pdfjs-dist/') || candidate.startsWith('@')) continue; // npm package paths
    if (!pathExists(candidate)) report(index, `\`${candidate}\` doesn't exist`);
  }

  // Relative links and @imports outside docs/ (VitePress checks the ones inside).
  if (!rel(file).startsWith('docs/')) {
    for (const match of text.matchAll(/\]\(([^)\s]+)\)/g)) {
      const target = match[1].split('#')[0];
      if (!target || /^[a-z]+:/i.test(target)) continue;
      const resolved = path.resolve(path.dirname(file), target);
      if (!existsSync(resolved) && !knownFiles.includes(rel(resolved))) report(match.index, `broken link to ${match[1]}`);
    }
    for (const match of text.matchAll(/^@(\S+)$/gm)) {
      const resolved = path.resolve(path.dirname(file), match[1]);
      if (!existsSync(resolved) || !statSync(resolved).isFile()) report(match.index, `@import of missing file ${match[1]}`);
    }
  }
}

if (problems.length > 0) {
  console.error(`check-docs: ${problems.length} problem(s):\n${problems.map((p) => `  - ${p}`).join('\n')}`);
  process.exit(1);
}
console.log(`check-docs: ${docFiles().length} files checked, no problem found`);
