/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReaderRouteImport } from './routes/reader'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ListsIndexRouteImport } from './routes/lists/index'
import { Route as ListsListIdRouteImport } from './routes/lists/$listId'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsDataRouteImport } from './routes/settings/data'
import { Route as SettingsLibraryRouteImport } from './routes/settings/library'
import { Route as SettingsMetadataRouteImport } from './routes/settings/metadata'
import { Route as SettingsReadingRouteImport } from './routes/settings/reading'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderRoute = ReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIndexRoute = ListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsListIdRoute = ListsListIdRouteImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLibraryRoute = SettingsLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMetadataRoute = SettingsMetadataRouteImport.update({
  id: '/metadata',
  path: '/metadata',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsReadingRoute = SettingsReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reader': typeof ReaderRoute
  '/settings': typeof SettingsRouteWithChildren
  '/lists/$listId': typeof ListsListIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/library': typeof SettingsLibraryRoute
  '/settings/metadata': typeof SettingsMetadataRoute
  '/settings/reading': typeof SettingsReadingRoute
  '/lists/': typeof ListsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reader': typeof ReaderRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/library': typeof SettingsLibraryRoute
  '/settings/metadata': typeof SettingsMetadataRoute
  '/settings/reading': typeof SettingsReadingRoute
  '/lists': typeof ListsIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reader': typeof ReaderRoute
  '/settings': typeof SettingsRouteWithChildren
  '/lists/$listId': typeof ListsListIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/library': typeof SettingsLibraryRoute
  '/settings/metadata': typeof SettingsMetadataRoute
  '/settings/reading': typeof SettingsReadingRoute
  '/lists/': typeof ListsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reader'
    | '/settings'
    | '/lists/$listId'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/data'
    | '/settings/library'
    | '/settings/metadata'
    | '/settings/reading'
    | '/lists/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reader'
    | '/lists/$listId'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/data'
    | '/settings/library'
    | '/settings/metadata'
    | '/settings/reading'
    | '/lists'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/reader'
    | '/settings'
    | '/lists/$listId'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/data'
    | '/settings/library'
    | '/settings/metadata'
    | '/settings/reading'
    | '/lists/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReaderRoute: typeof ReaderRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ListsListIdRoute: typeof ListsListIdRoute
  ListsIndexRoute: typeof ListsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader': {
      id: '/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof ReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/': {
      id: '/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof ListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$listId': {
      id: '/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof ListsListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/library': {
      id: '/settings/library'
      path: '/library'
      fullPath: '/settings/library'
      preLoaderRoute: typeof SettingsLibraryRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/metadata': {
      id: '/settings/metadata'
      path: '/metadata'
      fullPath: '/settings/metadata'
      preLoaderRoute: typeof SettingsMetadataRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/reading': {
      id: '/settings/reading'
      path: '/reading'
      fullPath: '/settings/reading'
      preLoaderRoute: typeof SettingsReadingRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsLibraryRoute: typeof SettingsLibraryRoute
  SettingsMetadataRoute: typeof SettingsMetadataRoute
  SettingsReadingRoute: typeof SettingsReadingRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsLibraryRoute: SettingsLibraryRoute,
  SettingsMetadataRoute: SettingsMetadataRoute,
  SettingsReadingRoute: SettingsReadingRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReaderRoute: ReaderRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ListsListIdRoute: ListsListIdRoute,
  ListsIndexRoute: ListsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
